# Placeholder Dockerfile for the worker service
# We will develop this further in Milestone 2
FROM node:20-alpine

WORKDIR /usr/src/app

# A placeholder command to keep the container running
CMD ["tail", "-f", "/dev/null"]
